spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
  cache:
    jcache:
      config: classpath:ehcache.xml
kkr:
  inventory:
    host: http://localhost:8082
