spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:beerdb
  jpa:
    defer-datasource-initialization: true
  cache:
    jcache:
      config: classpath:ehcache.xml
kkr:
  inventory:
    host: http://localhost:8082
